spring.application.name=userservice

spring.liquibase.change-log=db.changelog/db.changelog-master.xml

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/userservice}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}

spring.cache.type=redis
spring.data.redis.host=${REDIS_HOST:user-redis}
spring.data.redis.port=${REDIS_PORT:6379}

jwt.secret=${JWT_SECRET}
user.cards.limit=${USER_CARDS_LIMIT:5}

logging.level.com.innowise.userservice=DEBUG